### ISSUE TITLE
perception test video_feature problem

### ISSUE THREAD

**Issue by MuXiangWen** [JacobChalk/TIM#31]
i use the following command to extract video feature:
```
export CUDA_VISIBLE_DEVICES=6,7
python tools/run_net.py  --cfg /data/nvme2/dky/lc/TIM/feature_extractors/omnivore/configs/PERCEPTION_TEST/OMNIVORE_feature.yaml \
NUM_GPUS 2 \
OUTPUT_DIR /data/hdd/lishenshen/timfeature_data/perception_test-feature \
PERCEPTION.VISUAL_DATA_DIR /data/hdd/lishenshen/timframe_data/perception_test-frame/train_v \
PERCEPTION.TEST_LIST /data/nvme2/dky/lc/TIM/annotations/Perception_Test/Perception_Test_1_second_train_feature_times.pkl \
TEST.BATCH_SIZE 4 \
TEST.NUM_FEATURES 4
```
but there is an error :
`RuntimeError: stack expects each tensor to be equal size, but got [3, 32, 224, 49] at entry 0 and [3, 32, 224, 224] at entry 1`
and complete error is as follows:
```
Traceback (most recent call last):
  File "/data/nvme2/dky/lc/TIM/feature_extractors/omnivore/tools/run_net.py", line 103, in <module>
    main()
  File "/data/nvme2/dky/lc/TIM/feature_extractors/omnivore/tools/run_net.py", line 83, in main
    torch.multiprocessing.spawn(
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 241, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 158, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 68, in _wrap
    fn(i, *args)
  File "/data/nvme2/dky/lc/TIM/feature_extractors/omnivore/omnivore/utils/multiprocessing.py", line 50, in run
    func(cfg)
  File "/data/nvme2/dky/lc/TIM/feature_extractors/omnivore/tools/extract_features.py", line 125, in extract_features
    features, metadata = perform_feature_extraction(test_loader, model, test_meter, cfg)
  File "/data/nvme2/dky/lc/TIM/feature_extractors/omnivore/tools/extract_features.py", line 42, in perform_feature_extraction
    for cur_iter, (inputs, labels, video_idx, meta) in enumerate(test_loader):
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 277, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 144, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 144, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 121, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/data/nvme2/dky/miniconda3/envs/tim_video/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 174, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [3, 32, 224, 49] at entry 0 and [3, 32, 224, 224] at entry 1
```

i do not know how to fix it ,Thank You!

**Comment by JacobChalk** [comment]
Hi,

This was due to the presence of portrait videos in the Perception Test, resulting in some invalid crops (the 224x49 you see in the error). It has now been [fixed](https://github.com/JacobChalk/TIM/blob/d1c2819c79968adc4f176bc28a4b7989bf543b94/feature_extractors/omnivore/omnivore/datasets/perception.py#L128) and should work as intended. Apologies for any inconvenience!
